services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    volumes:
      - ./logs:/idealista_scrapper/logs
