services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - .:/idealista_scrapper

  celery-worker:
    build: .
    depends_on:
      - redis
    volumes:
      - .:/idealista_scrapper
    command: celery -A main:celery_app worker
