services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  api:
    build:
      dockerfile: Dockerfile.dev
    environment:
      - LOG_LEVEL=DEBUG # [DEBUG, INFO, WARNING, ERROR, CRITICAL]
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - ./logs:/idealista_scrapper/logs
      - ./src:/idealista_scrapper/src
    command: uv run uvicorn src.api.main:app --host 0.0.0.0 --reload

  celery-worker:
    build:
      dockerfile: Dockerfile.dev
    environment:
      - LOG_LEVEL=INFO # [DEBUG, INFO, WARNING, ERROR, CRITICAL]
    depends_on:
      - redis
    volumes:
      - ./logs:/idealista_scrapper/logs
      - ./src:/idealista_scrapper/src
    command: uv run celery -A src.core.celery worker
