services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  api:
    build: .
    environment:
      - LOG_LEVEL=DEBUG # [DEBUG, INFO, WARNING, ERROR, CRITICAL]
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - .:/idealista_scrapper

  celery-worker:
    build: .
    environment:
      - LOG_LEVEL=INFO # [DEBUG, INFO, WARNING, ERROR, CRITICAL]
    depends_on:
      - redis
    volumes:
      - .:/idealista_scrapper
    command: celery -A src.core.celery worker
