FROM python:3.11-slim

ENV PYTHONUNBUFFERED=1
SHELL ["/bin/bash", "-c"]


RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    curl \
    && rm -rf /var/lib/apt/lists/*


# Install uv and add to path
RUN curl -LsSf https://astral.sh/uv/install.sh | sh
ENV PATH="/root/.local/bin:${PATH}"


RUN git clone https://github.com/0865marc/idealista_scrapper.git
WORKDIR /idealista_scrapper

RUN uv sync
RUN mkdir logs


EXPOSE 8000

